language: python
python:
  - "3.5"
notifications:
  email:
    on_success: never
    on_failure: always
before_install:
  - mv travis/secrets.yaml secrets.yaml
install:
  - pip3 install homeassistant
script:
  - hass -c . --script check_config