- alias: 'Turn on Christmas lights at sunset'
  trigger:
    platform: sun
    event: sunset
    offset: "-00:10:00"
  action:
    service: switch.turn_on
    entity_id: switch.christmas_lights
- alias: 'Turn off Christmas lights at sunrise'
  trigger:
    platform: sun
    event: sunrise
    offset: "+01:00:00"
  action:
    service: switch.turn_off
    entity_id: switch.christmas_lights