- alias: 'Turn on bedroom lights at bedtime'
  trigger:
    platform: time
    at: '22:30:00'
  condition: 
    condition: state
    entity_id: group.all_devices
    state: 'home'
  action:
    service: light.turn_on
    entity_id: group.bedroom